#+TITLE:     Sample Beamer presentation
#+AUTHOR:    John Wiegley
#+EMAIL:     johnw@newartisans.com
#+DATE:      2018-01-27

#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  en

\setbeamertemplate{footline}{}
\setbeamerfont{block body}{size=\small}
\definecolor{orchid}{RGB}{134, 134, 220}
\definecolor{lightorchid}{RGB}{243, 243, 251}
\setbeamercolor{block title}{fg=white,bg=orchid}
\setbeamercolor{bgcolor}{fg=white,bg=blue}

* Introduction

** A simple slide

This slide consists of some text with a number of bullet points:

- the first, very @important@, point!
- the previous point shows the use of the special markup which translates to
  the Beamer specific /alert/ command for highlighting text.

The above list could be numbered or any other type of list and may
include sub-lists.

** A more complex slide

This slide illustrates the use of Beamer blocks.  The following text,
with its own headline, is displayed in a block:

*** Org mode increases productivity

- org mode means not having to remember LaTeX commands.
- it is based on ascii text which is inherently portable.
- Emacs!

\hfill \(\qed\)

** A block

- this slide consists of a list
- another item
- and another one...

** Test here

### Part.Chapter.Section.Test

# ** Babel

# *** Haskell code
# #+name: haskellexample
# #+begin_src haskell :exports results :results output
# putStrLn "Hello!"
# #+end_src

# #+results: haskellexample
# : Hello!

** Diagram!
#+name: graph-info-figure
#+begin_src plantuml :file diagram1.svg :java -Djava.awt.headless=true :results file
  Alice -> Bob: sync call
  Alice ->> Bob: async call
#+end_src

#+ATTR_LATEX: :height 4cm
#+results: graph-info-figure
[[file:diagram1.svg]]
** Another!
#+name: ditaa-figure
#+begin_src ditaa :file diagram2.svg :java -Djava.awt.headless=true :cmdline -T --svg :results file
+-----------+              +----------+
|   Foo     |              |   Bar    |
+------+----+              +------+---+
       |                          |
       |          +----------+    |
       |          |          +----+
       |          |    Baz   |
       \----------+          |
                  +----------+
#+end_src

#+ATTR_LATEX: :height 4cm
#+results: ditaa-figure
[[file:diagram2.svg]]
# ** A diagram
# *** Yet another!
# #+name: diagrams-figure
# #+BEGIN_SRC diagrams :file diagram3.svg :results file :width 400
# dia = circle 1 # fc cyan
# #+END_SRC

# #+ATTR_LATEX: :height 4cm
# #+results: diagrams-figure
# [[file:diagram3.svg]]
** Yet another!
  #+begin_export latex
\begin{tikzcd}
  T
  \arrow[drr, bend left, "x"]
  \arrow[ddr, bend right, "y"]
  \arrow[dr, dotted, "{(x,y)}" description] & & \\
    & X \times_Z Y \arrow[r, "p"] \arrow[d, "q"]
      & X \arrow[d, "f"] \\
    & Y \arrow[r, "g"] & Z
\end{tikzcd}
  #+end_export
** Can it be?!
#+name: dot-figure
#+begin_src dot :file diagram4.svg :cmdline -Tsvg :results file
digraph {
    bgcolor=transparent;
    rankdir=LR;
    2 [label=hello];
    1 -> 2 [color=red];
    1 -> 5 [color=red];
    2 -> 3 [color=green];
    3 -> 4 [color=blue];
    5 -> 6 [color=blue];
    6 -> 4 [color=blue];
}
#+end_src

#+ATTR_LATEX: :height 3cm
#+results: dot-figure
[[file:diagram4.svg]]
# ** A diagram
# *** Yet another!
# #+name: diagrams-figure
# #+BEGIN_SRC diagrams :file diagram5.svg :results file :width 400
# dia = circle 1 # fc red
# #+END_SRC

# #+ATTR_LATEX: :height 10cm
# #+results: diagrams-figure
# [[file:diagram5.svg]]
* Colophon

#+STARTUP: beamer
#+STARTUP: content fninline hidestars

#+OPTIONS: H:2 toc:nil

#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport

#+COLUMNS: %20ITEM %13BEAMER_env(Env) %6BEAMER_envargs(Args) %4BEAMER_col(Col) %7BEAMER_extra(Extra)

#+LaTeX_CLASS: beamer
#+LaTeX_CLASS_OPTIONS: [show notes, t]

#+LATEX_HEADER_EXTRA: \usepackage{courier}
#+LATEX_HEADER_EXTRA: \usepackage{helvet}
#+LATEX_HEADER_EXTRA: \usepackage{svg}
#+LATEX_HEADER_EXTRA: \usepackage{export}
#+LATEX_HEADER_EXTRA: \usepackage{pdfcomment}
#+LATEX_HEADER_EXTRA: \usepackage{unicode-math}
#+LATEX_HEADER_EXTRA: \usepackage{minted}
#+LATEX_HEADER_EXTRA: \usepackage{tikz}
#+LATEX_HEADER_EXTRA: \usepackage{tikz-cd}

#+BEAMER_THEME: [height=16mm] Rochester
#+BEAMER_COLOR: seahorse

#+BEAMER_HEADER: \setbeamertemplate{navigation symbols}{}
#+BEAMER_HEADER: \renewcommand{\note}[1]{\marginnote{\pdfcomment[icon=Note]{#1}}}
#+BEAMER_HEADER: \tikzcdset{/tikz/commutative diagrams/background color=lightorchid}
#+BEAMER_HEADER: \newcommand{\head}[1]{\begin{center}
#+BEAMER_HEADER: \vspace{13mm}\hspace{-1mm}\Huge{{#1}}
#+BEAMER_HEADER: \end{center}}
