name:          org-support-code
version:       0.1.0
synopsis:      Helper code to be using with org-beamer
github:        jwiegley/org-beamer-template
license:       MIT
author:        John Wiegley
maintainer:    johnw@newartisans.com
category:      Development

dependencies:      
  - base                 >= 4.9.1.0
  - bytestring           >= 0.10.8.1
  - containers           >= 0.5.7.1
  - hspec                >= 2.4.3
  - lens                 >= 4.15.1
  - lens-aeson           >= 1.0.0.5
  - mtl                  >= 2.2.1
  - text                 >= 1.2.2.1
  - thyme                >= 0.3.5.5
  - unordered-containers >= 0.2.8.0

tests:
  org-support-code:
    main: Main.hs
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
